channels:
- defaults
- conda-forge
dependencies:
- python=3.7.6
- pandas
- matplotlib
- pandas
- pip
- pip:
  - mlflow
  - tensorflow==2.3.0
  - matplotlib
  - scikit-learn==0.19.1
  - pandas  
name: mlflow-env
