channels:
- defaults
- conda-forge
dependencies:
- python=3.7.6
- pandas
- matplotlib
- sklearn
- warnings
- pandas
- pip
- pip:
  - mlflow
  - tensorflow==2.3.0
  - matplotlib
  - sklearn
  - warnings
  - pandas  
name: mlflow-env
